swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /directors:
    get:
      operationId: directors.read_all
      tags:
        - Directors
      summary: Read the entire set of director, sorted by id
      description: Read the entire set of director, sorted by id
      responses:
        200:
          description: Successfully read director set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the director
                name:
                  type: string
                  description: Name of the director
                gender:
                  type: string
                  description: Gender of the director
                uid:
                  type: integer
                  description: Uid of the director
                department:
                  type: string
                  description: Department of the director
                # notes:
                #   type: array
                #   items:
                #     properties:
                #       person_id:
                #         type: integer
                #         description: Id of person this note is associated with
                #       note_id:
                #         type: integer
                #         description: Id of this note
                #       content:
                #         type: string
                #         description: content of this note
                #       timestamp:
                #         type: string
                #         description: Create/Update timestamp of this note

    #POST
    post:
      operationId: directors.create
      tags:
        - Directors
      summary: Create a director
      description: Create a new director
      parameters:
        - name: director
          in: body
          description: Directors to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Uid of the director
              department:
                type: string
                description: Department of the director
      responses:
        201:
          description: Successfully created director
          schema:
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Uid of the director
              department:
                type: string
                description: Department of the director

  #GET by Id
  /directors/{id}:
    get:
      operationId: directors.read_one
      tags:
        - Directors
      summary: Read one director
      description: Read one director
      parameters:
        - name: id
          in: path
          description: Id of the director to get
          type: integer
          required: True
      responses:
        200:
          description: Successfully read director from people directors data operation
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Gender of the director
              department:
                type: string
                description: Department of the director
              # notes:
              #   type: array
              #   items:
              #     properties:
              #       person_id:
              #         type: integer
              #         description: Id of person this note is associated with
              #       note_id:
              #         type: integer
              #         description: Id of this note
              #       content:
              #         type: string
              #         description: content of this note
              #       timestamp:
              #         type: string
              #         description: Create/Update timestamp of this note

    #PUT
    put:
      operationId: directors.update
      tags:
        - Directors
      summary: Update a director
      description: Update a director
      parameters:
        - name: id
          in: path
          description: Id the director to update
          type: integer
          required: True
        - name: director
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Gender of the director
              department:
                type: string
                description: Department of the director
      responses:
        200:
          description: Successfully updated person
          schema:
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Gender of the director
              department:
                type: string
                description: Department of the director

    #DELETE
    delete:
      operationId: directors.delete
      tags:
        - Directors
      summary: Delete a director from the directors list
      description: Delete a director
      parameters:
        - name: id
          in: path
          type: integer
          description: Id of the director to delete
          required: true
      responses:
        200:
          description: Successfully deleted a director

  /directors/{name}:
    get:
      operationId: directors.read_one_name
      tags:
        - Directors
      summary: Read one name 
      description: Read one name 
      parameters:
        - name: name
          in: path
          description: Name of the director to get
          type: string
          required: True
      responses:
        200:
          description: Successfully read director from people directors data operation
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the director
              name:
                type: string
                description: Name of the director
              gender:
                type: integer
                description: Gender of the director
              uid:
                type: integer
                description: Gender of the director
              department:
                type: string
                description: Department of the director

  #GET movies
  /movies:
    get:
      operationId: movies.read_all
      tags:
        - Movies
      summary: Read the entire set of movies, sorted by id
      description: Read the entire set of movies, sorted by id
      responses:
        200:
          description: Successfully read movies for all direcctors operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                  description: Id of the movie
                original_title:
                  type: string
                  description: Title of the movie
                budget:
                  type: integer
                  description: Budget of the movie
                popularity:
                  type: integer
                  description: Popularity of the movie
                release_date:
                  type: string
                  description: Release date of the movie
                revenue:
                  type: integer
                  description: Revenue of the movie
                title:
                  type: string
                  description: Title of the movie
                vote_average:
                  type: number
                  description: Vote average of the movie
                vote_count:
                  type: integer
                  description: Vote count of the movie
                overview:
                  type: string
                  description: Overview of the movie
                tagline:
                  type: string
                  description: Tagline of the movie
                movie_uid:
                  type: integer
                  description: Uid of the movie
                director_id:
                  type: integer
                  description: Director id of the movie
                # person:
                #   type: object
                #   properties:
                #     person_id:
                #       type: integer
                #       description: Id of associated person
                #     fname:
                #       type: string
                #       description: Frist name of associated person
                #     lname:
                #       type: string
                #       description: Last name of associated person
                #     timestamp:
                #       type: string
                #       description: Create/Update timestamp of associated person


  #POST 
  /directors/{director_id}/movies:
    post:
      operationId: movies.create
      tags:
        - Movies
      summary: Create a movie associated with a director
      description: Create a movie associated with a director
      parameters:
        - name: director_id
          in: path
          description: Id of director associated with movie
          type: integer
          required: True
        - name: movie
          in: body
          description: Text content of the movie to create
          required: True
          schema:
            type: object
            properties:
              # id:
              #   type: integer
              #   description: Id of the movie
              original_title:
                type: string
                description: Title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              vote_count:
                type: integer
                description: Vote count of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: Tagline of the movie
              uid:
                type: integer
                description: Uid of the movie
              # director_id:
              #   type: integer
              #   description: Director id of the movie
      responses:
        201:
          description: Successfully created a movie
          schema:
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              vote_count:
                type: integer
                description: Vote count of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: Tagline of the movie
              uid:
                type: integer
                description: Uid of the movie
              director_id:
                type: integer
                description: Director id of the movie


  #GET
  /directors/{director_id}/movies/{movie_id}:
    get:
      operationId: movies.read_one
      tags:
        - Movies
      summary: Read a particular movie associated with a director
      description: Read a particular movie associated with a director
      parameters:
        - name: director_id
          in: path
          description: Id of director associated with movie
          type: integer
          required: True
        - name: movie_id
          in: path
          description: Id of movie
          type: integer
          required: True
      responses:
        200:
          description: Successfully read movie for a director
          schema:
            type: object
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              vote_count:
                type: integer
                description: Vote count of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: Tagline of the movie
              uid:
                type: integer
                description: Uid of the movie
              director_id:
                type: integer
                description: Director id of the movie
  

    #PUT
    put:
      operationId: movies.update
      tags:
        - Movies
      summary: Update a movie associated with a director
      description: Update a movie associated with a director
      parameters:
        - name: director_id
          in: path
          description: Id the director to update
          type: integer
          required: True
        - name: movie_id
          in: path
          description: Id of the movie associated with a director
          type: integer
          required: True
        - name: movie
          in: body
          schema:
            type: object
            properties:
              original_title:
                type: string
                description: Title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              vote_count:
                type: integer
                description: Vote count of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: Tagline of the movie
              uid:
                type: integer
                description: Uid of the movie
              # director_id:
              #   type: integer
              #   description: Director id of the movie
      responses:
        200:
          description: Successfully updated movie
          schema:
            properties:
              id:
                type: integer
                description: Id of the movie
              original_title:
                type: string
                description: Title of the movie
              budget:
                type: integer
                description: Budget of the movie
              popularity:
                type: integer
                description: Popularity of the movie
              release_date:
                type: string
                description: Release date of the movie
              revenue:
                type: integer
                description: Revenue of the movie
              title:
                type: string
                description: Title of the movie
              vote_average:
                type: number
                description: Vote average of the movie
              vote_count:
                type: integer
                description: Vote count of the movie
              overview:
                type: string
                description: Overview of the movie
              tagline:
                type: string
                description: Tagline of the movie
              uid:
                type: integer
                description: Uid of the movie
              director_id:
                type: integer
                description: Director id of the movie


    #DELETE
    delete:
      operationId: movies.delete
      tags:
        - Movies
      summary: Delete a movie associated with a director
      description: Delete a movie associated with a director
      parameters:
        - name: director_id
          in: path
          description: Id of director associated with movie
          type: integer
          required: True
        - name: movie_id
          in: path
          description: Id of movie
          type: integer
          required: True
      responses:
        200:
          description: Successfully deleted a movie